#!/usr/bin/env python3
"""Validate promising feature blocks across fixed CatBoost seeds and folds."""

from __future__ import annotations

import json
from pathlib import Path
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd
from sklearn.metrics import log_loss, roc_auc_score
from threadpoolctl import threadpool_limits

from scripts.train_archive_ensemble import load_saved_folds
from src.archive_ensemble.blend import disagreement_adjustment
from src.archive_ensemble.models import Recipe, fit_model
from src.feature_experiments import BASE_MODE, build_experiment_features
from src.pipeline import ID_COLUMN, load_competition_data, sha256_file


def main() -> int:
    ensemble = json.loads((ROOT / "ensemble_config.json").read_text())
    disagreement = json.loads((ROOT / "disagreement_config.json").read_text())
    data = load_competition_data(ROOT / "data" / "raw", ensemble["input_sha256"])
    fold_path = ROOT / ensemble["validation"]["folds_path"]
    if sha256_file(fold_path) != ensemble["validation"]["folds_sha256"]:
        raise ValueError("Saved folds changed")
    fold_id = load_saved_folds(fold_path, data.train, ensemble["validation"]["n_splits"])
    base = pd.read_csv(ROOT / "artifacts" / "archive_ensemble_v1" / "oof_predictions.csv")
    seed_base = pd.read_csv(ROOT / "artifacts" / "seed_bagging_v1" / "oof_predictions.csv")
    first = pd.read_csv(ROOT / "artifacts" / "feature_engineering_v1" / "oof_predictions.csv")
    if not (base[ID_COLUMN].equals(seed_base[ID_COLUMN]) and base[ID_COLUMN].equals(first[ID_COLUMN])):
        raise ValueError("OOF artifact IDs do not align")

    candidates = {
        "trajectory": ("trajectory",),
        "all_no_interactions": ("trajectory", "coverage", "trends", "bands"),
    }
    seeds = (137, 4099, 7919)
    recipe = Recipe(
        "feature_stability_cat",
        "catboost",
        BASE_MODE,
        dict(ensemble["models"][0]["params"]),
        status_categories=False,
    )
    base_matrix = base[disagreement["model_order"]].to_numpy()
    rows, columns = [], {}
    output = ROOT / "artifacts" / "feature_engineering_v1"

    with threadpool_limits(limits=6):
        for candidate, blocks in candidates.items():
            features = build_experiment_features(data.train, blocks)
            # Seed 2026 was already generated by the first ablation screen.
            columns[f"{candidate}__seed2026"] = first[f"cat__{candidate}"].to_numpy()
            for seed in seeds:
                oof = np.full(len(data.y), np.nan)
                for fold in range(ensemble["validation"]["n_splits"]):
                    train_rows, valid_rows = np.flatnonzero(fold_id != fold), np.flatnonzero(fold_id == fold)
                    started = time.perf_counter()
                    model, iteration = fit_model(
                        recipe,
                        features.iloc[train_rows],
                        data.y[train_rows],
                        features.iloc[valid_rows],
                        data.y[valid_rows],
                        seed=seed,
                        threads=6,
                    )
                    probability = model.predict(features.iloc[valid_rows])
                    oof[valid_rows] = probability
                    rows.append(
                        {
                            "candidate": candidate,
                            "seed": seed,
                            "fold": fold,
                            "best_iteration": iteration,
                            "cat_log_loss": log_loss(data.y[valid_rows], probability),
                            "runtime_seconds": time.perf_counter() - started,
                        }
                    )
                    print(f"{candidate} seed {seed} fold {fold}: {rows[-1]['cat_log_loss']:.9f}", flush=True)
                columns[f"{candidate}__seed{seed}"] = oof

    # Pair each engineered run with the same-seed base CatBoost prediction so
    # the feature effect is not confused with ordinary random-seed variation.
    summary = []
    base_by_seed = {2026: base["cat_behavior_d5"].to_numpy()}
    base_by_seed.update(
        {seed: seed_base[f"cat_behavior_d5__seed{seed}"].to_numpy() for seed in seeds}
    )
    for candidate in candidates:
        feature_predictions = []
        base_predictions = []
        for seed in (2026, *seeds):
            feature_cat = columns[f"{candidate}__seed{seed}"]
            feature_predictions.append(feature_cat)
            base_predictions.append(base_by_seed[seed])
            candidate_matrix, baseline_matrix = base_matrix.copy(), base_matrix.copy()
            candidate_matrix[:, 0], baseline_matrix[:, 0] = feature_cat, base_by_seed[seed]
            candidate_final = disagreement_adjustment(
                candidate_matrix, disagreement["base_weights"], disagreement["theta"]
            )
            baseline_final = disagreement_adjustment(
                baseline_matrix, disagreement["base_weights"], disagreement["theta"]
            )
            summary.append(
                {
                    "candidate": candidate,
                    "seed": seed,
                    "aggregation": "single_seed",
                    "final_log_loss": log_loss(data.y, candidate_final),
                    "paired_gain_vs_same_seed_base": log_loss(data.y, baseline_final)
                    - log_loss(data.y, candidate_final),
                    "final_roc_auc": roc_auc_score(data.y, candidate_final),
                }
            )
        candidate_matrix, baseline_matrix = base_matrix.copy(), base_matrix.copy()
        candidate_matrix[:, 0] = np.mean(feature_predictions, axis=0)
        baseline_matrix[:, 0] = np.mean(base_predictions, axis=0)
        candidate_final = disagreement_adjustment(
            candidate_matrix, disagreement["base_weights"], disagreement["theta"]
        )
        baseline_final = disagreement_adjustment(
            baseline_matrix, disagreement["base_weights"], disagreement["theta"]
        )
        summary.append(
            {
                "candidate": candidate,
                "seed": "mean_4",
                "aggregation": "equal_seed_average",
                "final_log_loss": log_loss(data.y, candidate_final),
                "paired_gain_vs_same_seed_base": log_loss(data.y, baseline_final)
                - log_loss(data.y, candidate_final),
                "final_roc_auc": roc_auc_score(data.y, candidate_final),
            }
        )

    pd.DataFrame({ID_COLUMN: data.train[ID_COLUMN], "target": data.y, "fold": fold_id, **columns}).to_csv(
        output / "stability_oof_predictions.csv", index=False, float_format="%.12g"
    )
    pd.DataFrame(rows).to_csv(output / "stability_fold_metrics.csv", index=False, float_format="%.12g")
    pd.DataFrame(summary).to_csv(output / "stability_summary.csv", index=False, float_format="%.12g")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
